"""initial AXIS schema

Revision ID: 20260829_0001
Revises:
Create Date: 2026-08-29 19:20:03.051878
"""

from collections.abc import Sequence

import sqlalchemy as sa
from alembic import op

revision: str = "20260829_0001"
down_revision: str | None = None
branch_labels: str | Sequence[str] | None = None
depends_on: str | Sequence[str] | None = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table(
        "guild_config",
        sa.Column("guild_id", sa.BigInteger(), autoincrement=False, nullable=False),
        sa.Column("timezone", sa.String(length=64), nullable=False),
        sa.Column("subscription_url", sa.Text(), nullable=True),
        sa.Column("weekly_results_enabled", sa.Boolean(), nullable=False),
        sa.Column("lab_enabled", sa.Boolean(), nullable=False),
        sa.Column("manager_role_id", sa.BigInteger(), nullable=True),
        sa.Column("member_role_id", sa.BigInteger(), nullable=True),
        sa.Column("results_channel_id", sa.BigInteger(), nullable=True),
        sa.Column("short_term_channel_id", sa.BigInteger(), nullable=True),
        sa.Column("swing_channel_id", sa.BigInteger(), nullable=True),
        sa.Column("leaps_channel_id", sa.BigInteger(), nullable=True),
        sa.Column("mentor_control_channel_id", sa.BigInteger(), nullable=True),
        sa.Column("member_control_channel_id", sa.BigInteger(), nullable=True),
        sa.Column("mentor_panel_message_id", sa.BigInteger(), nullable=True),
        sa.Column("member_panel_message_id", sa.BigInteger(), nullable=True),
        sa.Column(
            "created_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("(CURRENT_TIMESTAMP)"),
            nullable=False,
        ),
        sa.Column(
            "updated_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("(CURRENT_TIMESTAMP)"),
            nullable=False,
        ),
        sa.PrimaryKeyConstraint("guild_id", name=op.f("pk_guild_config")),
    )
    op.create_table(
        "audit_logs",
        sa.Column("guild_id", sa.BigInteger(), nullable=False),
        sa.Column("actor_user_id", sa.BigInteger(), nullable=False),
        sa.Column("action_type", sa.String(length=64), nullable=False),
        sa.Column("entity_type", sa.String(length=64), nullable=False),
        sa.Column("entity_id", sa.String(length=64), nullable=False),
        sa.Column("before_json", sa.JSON(), nullable=True),
        sa.Column("after_json", sa.JSON(), nullable=True),
        sa.Column("discord_interaction_id", sa.BigInteger(), nullable=True),
        sa.Column(
            "created_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("(CURRENT_TIMESTAMP)"),
            nullable=False,
        ),
        sa.Column("id", sa.Uuid(), nullable=False),
        sa.ForeignKeyConstraint(
            ["guild_id"],
            ["guild_config.guild_id"],
            name=op.f("fk_audit_logs_guild_id_guild_config"),
            ondelete="CASCADE",
        ),
        sa.PrimaryKeyConstraint("id", name=op.f("pk_audit_logs")),
    )
    op.create_index(
        op.f("ix_audit_logs_actor_user_id"), "audit_logs", ["actor_user_id"], unique=False
    )
    op.create_index(
        "ix_audit_logs_guild_created", "audit_logs", ["guild_id", "created_at"], unique=False
    )
    op.create_index(op.f("ix_audit_logs_guild_id"), "audit_logs", ["guild_id"], unique=False)
    op.create_table(
        "memberships",
        sa.Column("guild_id", sa.BigInteger(), nullable=False),
        sa.Column("user_id", sa.BigInteger(), nullable=False),
        sa.Column("status", sa.String(length=16), nullable=False),
        sa.Column("source", sa.String(length=16), nullable=False),
        sa.Column("starts_at", sa.DateTime(timezone=True), nullable=False),
        sa.Column("ends_at", sa.DateTime(timezone=True), nullable=True),
        sa.Column("cancel_at_period_end", sa.Boolean(), nullable=False),
        sa.Column("created_by", sa.BigInteger(), nullable=True),
        sa.Column("removal_reason", sa.Text(), nullable=True),
        sa.Column("version", sa.Integer(), nullable=False),
        sa.Column("id", sa.Uuid(), nullable=False),
        sa.Column(
            "created_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("(CURRENT_TIMESTAMP)"),
            nullable=False,
        ),
        sa.Column(
            "updated_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("(CURRENT_TIMESTAMP)"),
            nullable=False,
        ),
        sa.CheckConstraint(
            "source IN ('MANUAL', 'GIFT', 'PAYMENT', 'IMPORT')",
            name=op.f("ck_memberships_membership_source"),
        ),
        sa.CheckConstraint(
            "status IN ('ACTIVE', 'EXPIRED', 'CANCELLED', 'REMOVED')",
            name=op.f("ck_memberships_membership_status"),
        ),
        sa.ForeignKeyConstraint(
            ["guild_id"],
            ["guild_config.guild_id"],
            name=op.f("fk_memberships_guild_id_guild_config"),
            ondelete="CASCADE",
        ),
        sa.PrimaryKeyConstraint("id", name=op.f("pk_memberships")),
        sa.UniqueConstraint("guild_id", "user_id", name="membership_user_per_guild"),
    )
    op.create_index(op.f("ix_memberships_ends_at"), "memberships", ["ends_at"], unique=False)
    op.create_index(op.f("ix_memberships_guild_id"), "memberships", ["guild_id"], unique=False)
    op.create_index(op.f("ix_memberships_user_id"), "memberships", ["user_id"], unique=False)
    op.create_table(
        "mentors",
        sa.Column("guild_id", sa.BigInteger(), nullable=False),
        sa.Column("name", sa.String(length=100), nullable=False),
        sa.Column("short_code", sa.String(length=24), nullable=False),
        sa.Column("is_active", sa.Boolean(), nullable=False),
        sa.Column("id", sa.Uuid(), nullable=False),
        sa.Column(
            "created_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("(CURRENT_TIMESTAMP)"),
            nullable=False,
        ),
        sa.Column(
            "updated_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("(CURRENT_TIMESTAMP)"),
            nullable=False,
        ),
        sa.ForeignKeyConstraint(
            ["guild_id"],
            ["guild_config.guild_id"],
            name=op.f("fk_mentors_guild_id_guild_config"),
            ondelete="CASCADE",
        ),
        sa.PrimaryKeyConstraint("id", name=op.f("pk_mentors")),
        sa.UniqueConstraint("guild_id", "name", name="mentor_name_per_guild"),
        sa.UniqueConstraint("guild_id", "short_code", name="mentor_code_per_guild"),
    )
    op.create_index(op.f("ix_mentors_guild_id"), "mentors", ["guild_id"], unique=False)
    op.create_table(
        "scheduled_jobs",
        sa.Column("guild_id", sa.BigInteger(), nullable=True),
        sa.Column("job_type", sa.String(length=64), nullable=False),
        sa.Column("dedupe_key", sa.String(length=255), nullable=False),
        sa.Column("status", sa.String(length=16), nullable=False),
        sa.Column("run_at", sa.DateTime(timezone=True), nullable=False),
        sa.Column("attempts", sa.Integer(), nullable=False),
        sa.Column("max_attempts", sa.Integer(), nullable=False),
        sa.Column("locked_at", sa.DateTime(timezone=True), nullable=True),
        sa.Column("locked_by", sa.String(length=100), nullable=True),
        sa.Column("last_error", sa.Text(), nullable=True),
        sa.Column("payload", sa.JSON(), nullable=False),
        sa.Column("id", sa.Uuid(), nullable=False),
        sa.Column(
            "created_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("(CURRENT_TIMESTAMP)"),
            nullable=False,
        ),
        sa.Column(
            "updated_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("(CURRENT_TIMESTAMP)"),
            nullable=False,
        ),
        sa.CheckConstraint(
            "status IN ('PENDING', 'RUNNING', 'SUCCEEDED', 'FAILED', 'CANCELLED')",
            name=op.f("ck_scheduled_jobs_scheduled_job_status"),
        ),
        sa.CheckConstraint("attempts >= 0", name=op.f("ck_scheduled_jobs_scheduled_job_attempts")),
        sa.CheckConstraint(
            "max_attempts > 0", name=op.f("ck_scheduled_jobs_scheduled_job_max_attempts")
        ),
        sa.ForeignKeyConstraint(
            ["guild_id"],
            ["guild_config.guild_id"],
            name=op.f("fk_scheduled_jobs_guild_id_guild_config"),
            ondelete="CASCADE",
        ),
        sa.PrimaryKeyConstraint("id", name=op.f("pk_scheduled_jobs")),
        sa.UniqueConstraint("dedupe_key", name="scheduled_job_dedupe_key"),
    )
    op.create_index("ix_scheduled_jobs_due", "scheduled_jobs", ["status", "run_at"], unique=False)
    op.create_index(
        op.f("ix_scheduled_jobs_guild_id"), "scheduled_jobs", ["guild_id"], unique=False
    )
    op.create_table(
        "source_messages",
        sa.Column("guild_id", sa.BigInteger(), nullable=False),
        sa.Column("discord_message_id", sa.BigInteger(), nullable=False),
        sa.Column("channel_id", sa.BigInteger(), nullable=False),
        sa.Column("submitted_by", sa.BigInteger(), nullable=False),
        sa.Column("raw_text", sa.Text(), nullable=True),
        sa.Column("status", sa.String(length=24), nullable=False),
        sa.Column("received_at", sa.DateTime(timezone=True), nullable=False),
        sa.Column(
            "created_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("(CURRENT_TIMESTAMP)"),
            nullable=False,
        ),
        sa.Column("id", sa.Uuid(), nullable=False),
        sa.CheckConstraint(
            "status IN ('RECEIVED', 'PROCESSING', 'PARSED', 'REJECTED', 'FAILED')",
            name=op.f("ck_source_messages_source_status"),
        ),
        sa.ForeignKeyConstraint(
            ["guild_id"],
            ["guild_config.guild_id"],
            name=op.f("fk_source_messages_guild_id_guild_config"),
            ondelete="CASCADE",
        ),
        sa.PrimaryKeyConstraint("id", name=op.f("pk_source_messages")),
        sa.UniqueConstraint("guild_id", "discord_message_id", name="source_message_per_guild"),
    )
    op.create_index(
        op.f("ix_source_messages_guild_id"), "source_messages", ["guild_id"], unique=False
    )
    op.create_index(
        op.f("ix_source_messages_submitted_by"), "source_messages", ["submitted_by"], unique=False
    )
    op.create_table(
        "subscriptions",
        sa.Column("guild_id", sa.BigInteger(), nullable=False),
        sa.Column("user_id", sa.BigInteger(), nullable=False),
        sa.Column("provider", sa.String(length=32), nullable=False),
        sa.Column("external_customer_id", sa.String(length=255), nullable=True),
        sa.Column("external_subscription_id", sa.String(length=255), nullable=True),
        sa.Column("status", sa.String(length=32), nullable=False),
        sa.Column("current_period_start", sa.DateTime(timezone=True), nullable=True),
        sa.Column("current_period_end", sa.DateTime(timezone=True), nullable=True),
        sa.Column("cancel_at_period_end", sa.Boolean(), nullable=False),
        sa.Column("id", sa.Uuid(), nullable=False),
        sa.Column(
            "created_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("(CURRENT_TIMESTAMP)"),
            nullable=False,
        ),
        sa.Column(
            "updated_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("(CURRENT_TIMESTAMP)"),
            nullable=False,
        ),
        sa.ForeignKeyConstraint(
            ["guild_id"],
            ["guild_config.guild_id"],
            name=op.f("fk_subscriptions_guild_id_guild_config"),
            ondelete="CASCADE",
        ),
        sa.PrimaryKeyConstraint("id", name=op.f("pk_subscriptions")),
        sa.UniqueConstraint("provider", "external_subscription_id", name="provider_subscription"),
    )
    op.create_index(op.f("ix_subscriptions_guild_id"), "subscriptions", ["guild_id"], unique=False)
    op.create_index(op.f("ix_subscriptions_user_id"), "subscriptions", ["user_id"], unique=False)
    op.create_table(
        "membership_events",
        sa.Column("membership_id", sa.Uuid(), nullable=False),
        sa.Column("action", sa.String(length=32), nullable=False),
        sa.Column("source", sa.String(length=16), nullable=False),
        sa.Column("actor_user_id", sa.BigInteger(), nullable=True),
        sa.Column("before_json", sa.JSON(), nullable=True),
        sa.Column("after_json", sa.JSON(), nullable=True),
        sa.Column("reason", sa.Text(), nullable=True),
        sa.Column(
            "created_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("(CURRENT_TIMESTAMP)"),
            nullable=False,
        ),
        sa.Column("id", sa.Uuid(), nullable=False),
        sa.ForeignKeyConstraint(
            ["membership_id"],
            ["memberships.id"],
            name=op.f("fk_membership_events_membership_id_memberships"),
            ondelete="CASCADE",
        ),
        sa.PrimaryKeyConstraint("id", name=op.f("pk_membership_events")),
    )
    op.create_index(
        "ix_membership_events_membership_created",
        "membership_events",
        ["membership_id", "created_at"],
        unique=False,
    )
    op.create_index(
        op.f("ix_membership_events_membership_id"),
        "membership_events",
        ["membership_id"],
        unique=False,
    )
    op.create_table(
        "mentor_aliases",
        sa.Column("guild_id", sa.BigInteger(), nullable=False),
        sa.Column("mentor_id", sa.Uuid(), nullable=False),
        sa.Column("alias", sa.String(length=100), nullable=False),
        sa.Column("normalized_alias", sa.String(length=100), nullable=False),
        sa.Column(
            "created_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("(CURRENT_TIMESTAMP)"),
            nullable=False,
        ),
        sa.Column("id", sa.Uuid(), nullable=False),
        sa.ForeignKeyConstraint(
            ["guild_id"],
            ["guild_config.guild_id"],
            name=op.f("fk_mentor_aliases_guild_id_guild_config"),
            ondelete="CASCADE",
        ),
        sa.ForeignKeyConstraint(
            ["mentor_id"],
            ["mentors.id"],
            name=op.f("fk_mentor_aliases_mentor_id_mentors"),
            ondelete="CASCADE",
        ),
        sa.PrimaryKeyConstraint("id", name=op.f("pk_mentor_aliases")),
        sa.UniqueConstraint("guild_id", "normalized_alias", name="mentor_alias_per_guild"),
    )
    op.create_index(
        op.f("ix_mentor_aliases_guild_id"), "mentor_aliases", ["guild_id"], unique=False
    )
    op.create_index(
        op.f("ix_mentor_aliases_mentor_id"), "mentor_aliases", ["mentor_id"], unique=False
    )
    op.create_table(
        "source_attachments",
        sa.Column("source_message_id", sa.Uuid(), nullable=False),
        sa.Column("discord_attachment_id", sa.BigInteger(), nullable=False),
        sa.Column("filename", sa.String(length=255), nullable=False),
        sa.Column("content_type", sa.String(length=100), nullable=False),
        sa.Column("size_bytes", sa.BigInteger(), nullable=False),
        sa.Column("source_url", sa.Text(), nullable=True),
        sa.Column("storage_key", sa.String(length=500), nullable=True),
        sa.Column("checksum_sha256", sa.String(length=64), nullable=True),
        sa.Column(
            "created_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("(CURRENT_TIMESTAMP)"),
            nullable=False,
        ),
        sa.Column("id", sa.Uuid(), nullable=False),
        sa.CheckConstraint(
            "size_bytes >= 0", name=op.f("ck_source_attachments_attachment_size_nonnegative")
        ),
        sa.ForeignKeyConstraint(
            ["source_message_id"],
            ["source_messages.id"],
            name=op.f("fk_source_attachments_source_message_id_source_messages"),
            ondelete="CASCADE",
        ),
        sa.PrimaryKeyConstraint("id", name=op.f("pk_source_attachments")),
    )
    op.create_index(
        op.f("ix_source_attachments_source_message_id"),
        "source_attachments",
        ["source_message_id"],
        unique=False,
    )
    op.create_table(
        "trades",
        sa.Column("guild_id", sa.BigInteger(), nullable=False),
        sa.Column("public_trade_id", sa.String(length=32), nullable=False),
        sa.Column("category", sa.String(length=32), nullable=False),
        sa.Column("mentor_id", sa.Uuid(), nullable=False),
        sa.Column("ticker", sa.String(length=12), nullable=False),
        sa.Column("expiry", sa.Date(), nullable=False),
        sa.Column("strike", sa.Numeric(precision=18, scale=4), nullable=False),
        sa.Column("option_side", sa.String(length=16), nullable=False),
        sa.Column("state", sa.String(length=16), nullable=False),
        sa.Column("last_public_action", sa.String(length=32), nullable=True),
        sa.Column("position_eighths", sa.SmallInteger(), nullable=False),
        sa.Column("max_position_eighths", sa.SmallInteger(), nullable=False),
        sa.Column("entry_low", sa.Numeric(precision=18, scale=4), nullable=True),
        sa.Column("entry_high", sa.Numeric(precision=18, scale=4), nullable=True),
        sa.Column("avg_cost", sa.Numeric(precision=18, scale=4), nullable=True),
        sa.Column("sl", sa.Numeric(precision=18, scale=4), nullable=True),
        sa.Column("tp1", sa.Numeric(precision=18, scale=4), nullable=True),
        sa.Column("tp2", sa.Numeric(precision=18, scale=4), nullable=True),
        sa.Column("opened_at", sa.DateTime(timezone=True), nullable=True),
        sa.Column("closed_at", sa.DateTime(timezone=True), nullable=True),
        sa.Column("version", sa.Integer(), nullable=False),
        sa.Column("id", sa.Uuid(), nullable=False),
        sa.Column(
            "created_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("(CURRENT_TIMESTAMP)"),
            nullable=False,
        ),
        sa.Column(
            "updated_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("(CURRENT_TIMESTAMP)"),
            nullable=False,
        ),
        sa.CheckConstraint(
            "category IN ('SHORT_TERM', 'SWING', 'LEAPS')", name=op.f("ck_trades_trade_category")
        ),
        sa.CheckConstraint(
            "option_side IN ('CALL', 'PUT')", name=op.f("ck_trades_trade_option_side")
        ),
        sa.CheckConstraint(
            "state IN ('DRAFT', 'ACTIVE', 'RUNNER', 'CLOSED', 'CANCELLED')",
            name=op.f("ck_trades_trade_state"),
        ),
        sa.CheckConstraint(
            "entry_low IS NULL OR entry_high IS NULL OR entry_low <= entry_high",
            name=op.f("ck_trades_trade_entry_range"),
        ),
        sa.CheckConstraint(
            "max_position_eighths BETWEEN 0 AND 8", name=op.f("ck_trades_trade_max_position")
        ),
        sa.CheckConstraint(
            "position_eighths BETWEEN 0 AND 8", name=op.f("ck_trades_trade_position")
        ),
        sa.ForeignKeyConstraint(
            ["guild_id"],
            ["guild_config.guild_id"],
            name=op.f("fk_trades_guild_id_guild_config"),
            ondelete="CASCADE",
        ),
        sa.ForeignKeyConstraint(
            ["mentor_id"],
            ["mentors.id"],
            name=op.f("fk_trades_mentor_id_mentors"),
            ondelete="RESTRICT",
        ),
        sa.PrimaryKeyConstraint("id", name=op.f("pk_trades")),
        sa.UniqueConstraint("guild_id", "public_trade_id", name="public_trade_id_per_guild"),
    )
    op.create_index(op.f("ix_trades_guild_id"), "trades", ["guild_id"], unique=False)
    op.create_index(
        "ix_trades_guild_state_category", "trades", ["guild_id", "state", "category"], unique=False
    )
    op.create_index(op.f("ix_trades_mentor_id"), "trades", ["mentor_id"], unique=False)
    op.create_table(
        "trade_drafts",
        sa.Column("guild_id", sa.BigInteger(), nullable=False),
        sa.Column("draft_code", sa.String(length=32), nullable=False),
        sa.Column("source_message_id", sa.Uuid(), nullable=False),
        sa.Column("matched_trade_id", sa.Uuid(), nullable=True),
        sa.Column("mentor_id", sa.Uuid(), nullable=True),
        sa.Column("status", sa.String(length=32), nullable=False),
        sa.Column("intent", sa.String(length=32), nullable=False),
        sa.Column("action", sa.String(length=32), nullable=False),
        sa.Column("action_stage", sa.String(length=16), nullable=True),
        sa.Column("category_suggestion", sa.String(length=32), nullable=True),
        sa.Column("selected_category", sa.String(length=32), nullable=True),
        sa.Column("ticker", sa.String(length=12), nullable=True),
        sa.Column("expiry", sa.Date(), nullable=True),
        sa.Column("strike", sa.Numeric(precision=18, scale=4), nullable=True),
        sa.Column("option_side", sa.String(length=16), nullable=True),
        sa.Column("entry_low", sa.Numeric(precision=18, scale=4), nullable=True),
        sa.Column("entry_high", sa.Numeric(precision=18, scale=4), nullable=True),
        sa.Column("action_price", sa.Numeric(precision=18, scale=4), nullable=True),
        sa.Column("avg_cost", sa.Numeric(precision=18, scale=4), nullable=True),
        sa.Column("sl", sa.Numeric(precision=18, scale=4), nullable=True),
        sa.Column("tp1", sa.Numeric(precision=18, scale=4), nullable=True),
        sa.Column("tp2", sa.Numeric(precision=18, scale=4), nullable=True),
        sa.Column("position_delta_eighths", sa.SmallInteger(), nullable=True),
        sa.Column("position_after_eighths", sa.SmallInteger(), nullable=True),
        sa.Column("current_pnl_pct", sa.Numeric(precision=10, scale=4), nullable=True),
        sa.Column("mentor_hint", sa.String(length=100), nullable=True),
        sa.Column("parser_confidence", sa.Numeric(precision=6, scale=5), nullable=True),
        sa.Column("parse_payload", sa.JSON(), nullable=False),
        sa.Column("missing_fields", sa.JSON(), nullable=False),
        sa.Column("warnings", sa.JSON(), nullable=False),
        sa.Column("internal_notes", sa.Text(), nullable=True),
        sa.Column("reviewed_by", sa.BigInteger(), nullable=True),
        sa.Column("version", sa.Integer(), nullable=False),
        sa.Column("id", sa.Uuid(), nullable=False),
        sa.Column(
            "created_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("(CURRENT_TIMESTAMP)"),
            nullable=False,
        ),
        sa.Column(
            "updated_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("(CURRENT_TIMESTAMP)"),
            nullable=False,
        ),
        sa.CheckConstraint(
            "status IN ('PENDING_REVIEW', 'PARSE_FAILED', 'READY', "
            "'PUBLISHED', 'PUBLISH_FAILED', 'DELETED')",
            name=op.f("ck_trade_drafts_draft_status"),
        ),
        sa.CheckConstraint(
            "parser_confidence BETWEEN 0 AND 1", name=op.f("ck_trade_drafts_parser_confidence")
        ),
        sa.CheckConstraint(
            "position_after_eighths BETWEEN 0 AND 8",
            name=op.f("ck_trade_drafts_draft_position_after"),
        ),
        sa.CheckConstraint(
            "position_delta_eighths BETWEEN -8 AND 8",
            name=op.f("ck_trade_drafts_draft_position_delta"),
        ),
        sa.ForeignKeyConstraint(
            ["guild_id"],
            ["guild_config.guild_id"],
            name=op.f("fk_trade_drafts_guild_id_guild_config"),
            ondelete="CASCADE",
        ),
        sa.ForeignKeyConstraint(
            ["matched_trade_id"],
            ["trades.id"],
            name=op.f("fk_trade_drafts_matched_trade_id_trades"),
            ondelete="SET NULL",
        ),
        sa.ForeignKeyConstraint(
            ["mentor_id"],
            ["mentors.id"],
            name=op.f("fk_trade_drafts_mentor_id_mentors"),
            ondelete="SET NULL",
        ),
        sa.ForeignKeyConstraint(
            ["source_message_id"],
            ["source_messages.id"],
            name=op.f("fk_trade_drafts_source_message_id_source_messages"),
            ondelete="RESTRICT",
        ),
        sa.PrimaryKeyConstraint("id", name=op.f("pk_trade_drafts")),
        sa.UniqueConstraint("guild_id", "draft_code", name="draft_code_per_guild"),
    )
    op.create_index(op.f("ix_trade_drafts_guild_id"), "trade_drafts", ["guild_id"], unique=False)
    op.create_index(
        op.f("ix_trade_drafts_matched_trade_id"), "trade_drafts", ["matched_trade_id"], unique=False
    )
    op.create_index(op.f("ix_trade_drafts_mentor_id"), "trade_drafts", ["mentor_id"], unique=False)
    op.create_index(
        op.f("ix_trade_drafts_source_message_id"),
        "trade_drafts",
        ["source_message_id"],
        unique=False,
    )
    op.create_table(
        "trade_events",
        sa.Column("trade_id", sa.Uuid(), nullable=False),
        sa.Column("action", sa.String(length=32), nullable=False),
        sa.Column("action_stage", sa.String(length=16), nullable=False),
        sa.Column("price", sa.Numeric(precision=18, scale=4), nullable=True),
        sa.Column("position_delta_eighths", sa.SmallInteger(), nullable=False),
        sa.Column("position_after_eighths", sa.SmallInteger(), nullable=False),
        sa.Column("avg_cost_after", sa.Numeric(precision=18, scale=4), nullable=True),
        sa.Column("pnl_pct", sa.Numeric(precision=10, scale=4), nullable=True),
        sa.Column("sl_before", sa.Numeric(precision=18, scale=4), nullable=True),
        sa.Column("sl_after", sa.Numeric(precision=18, scale=4), nullable=True),
        sa.Column("tp1_after", sa.Numeric(precision=18, scale=4), nullable=True),
        sa.Column("tp2_after", sa.Numeric(precision=18, scale=4), nullable=True),
        sa.Column("source_message_id", sa.Uuid(), nullable=True),
        sa.Column("draft_id", sa.Uuid(), nullable=True),
        sa.Column("approved_by", sa.BigInteger(), nullable=False),
        sa.Column("published_message_id", sa.BigInteger(), nullable=True),
        sa.Column(
            "created_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("(CURRENT_TIMESTAMP)"),
            nullable=False,
        ),
        sa.Column("id", sa.Uuid(), nullable=False),
        sa.CheckConstraint(
            "action IN ('ENTRY', 'ADD', 'UPDATE', 'TP1', 'TP2', 'RUNNER', "
            "'PARTIAL_SL', 'SL', 'CLOSE', 'CANCEL', 'ROLL')",
            name=op.f("ck_trade_events_trade_event_action"),
        ),
        sa.CheckConstraint(
            "action_stage IN ('NONE', 'FIRST', 'SECOND', 'THIRD', 'FOURTH')",
            name=op.f("ck_trade_events_trade_event_stage"),
        ),
        sa.CheckConstraint(
            "position_after_eighths BETWEEN 0 AND 8",
            name=op.f("ck_trade_events_event_position_after"),
        ),
        sa.CheckConstraint(
            "position_delta_eighths BETWEEN -8 AND 8",
            name=op.f("ck_trade_events_event_position_delta"),
        ),
        sa.ForeignKeyConstraint(
            ["draft_id"],
            ["trade_drafts.id"],
            name=op.f("fk_trade_events_draft_id_trade_drafts"),
            ondelete="SET NULL",
        ),
        sa.ForeignKeyConstraint(
            ["source_message_id"],
            ["source_messages.id"],
            name=op.f("fk_trade_events_source_message_id_source_messages"),
            ondelete="SET NULL",
        ),
        sa.ForeignKeyConstraint(
            ["trade_id"],
            ["trades.id"],
            name=op.f("fk_trade_events_trade_id_trades"),
            ondelete="CASCADE",
        ),
        sa.PrimaryKeyConstraint("id", name=op.f("pk_trade_events")),
    )
    op.create_index(op.f("ix_trade_events_draft_id"), "trade_events", ["draft_id"], unique=False)
    op.create_index(
        op.f("ix_trade_events_source_message_id"),
        "trade_events",
        ["source_message_id"],
        unique=False,
    )
    op.create_index(
        "ix_trade_events_trade_created", "trade_events", ["trade_id", "created_at"], unique=False
    )
    op.create_index(op.f("ix_trade_events_trade_id"), "trade_events", ["trade_id"], unique=False)
    op.create_table(
        "public_messages",
        sa.Column("guild_id", sa.BigInteger(), nullable=False),
        sa.Column("trade_id", sa.Uuid(), nullable=True),
        sa.Column("trade_event_id", sa.Uuid(), nullable=True),
        sa.Column("message_type", sa.String(length=32), nullable=False),
        sa.Column("channel_id", sa.BigInteger(), nullable=False),
        sa.Column("message_id", sa.BigInteger(), nullable=False),
        sa.Column("custom_id", sa.String(length=100), nullable=True),
        sa.Column("payload_hash", sa.String(length=64), nullable=True),
        sa.Column(
            "created_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("(CURRENT_TIMESTAMP)"),
            nullable=False,
        ),
        sa.Column("corrected_at", sa.DateTime(timezone=True), nullable=True),
        sa.Column("id", sa.Uuid(), nullable=False),
        sa.ForeignKeyConstraint(
            ["guild_id"],
            ["guild_config.guild_id"],
            name=op.f("fk_public_messages_guild_id_guild_config"),
            ondelete="CASCADE",
        ),
        sa.ForeignKeyConstraint(
            ["trade_event_id"],
            ["trade_events.id"],
            name=op.f("fk_public_messages_trade_event_id_trade_events"),
            ondelete="SET NULL",
        ),
        sa.ForeignKeyConstraint(
            ["trade_id"],
            ["trades.id"],
            name=op.f("fk_public_messages_trade_id_trades"),
            ondelete="SET NULL",
        ),
        sa.PrimaryKeyConstraint("id", name=op.f("pk_public_messages")),
        sa.UniqueConstraint("guild_id", "message_id", name="public_message_per_guild"),
    )
    op.create_index(
        op.f("ix_public_messages_guild_id"), "public_messages", ["guild_id"], unique=False
    )
    op.create_index(
        op.f("ix_public_messages_trade_event_id"),
        "public_messages",
        ["trade_event_id"],
        unique=False,
    )
    op.create_index(
        op.f("ix_public_messages_trade_id"), "public_messages", ["trade_id"], unique=False
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f("ix_public_messages_trade_id"), table_name="public_messages")
    op.drop_index(op.f("ix_public_messages_trade_event_id"), table_name="public_messages")
    op.drop_index(op.f("ix_public_messages_guild_id"), table_name="public_messages")
    op.drop_table("public_messages")
    op.drop_index(op.f("ix_trade_events_trade_id"), table_name="trade_events")
    op.drop_index("ix_trade_events_trade_created", table_name="trade_events")
    op.drop_index(op.f("ix_trade_events_source_message_id"), table_name="trade_events")
    op.drop_index(op.f("ix_trade_events_draft_id"), table_name="trade_events")
    op.drop_table("trade_events")
    op.drop_index(op.f("ix_trade_drafts_source_message_id"), table_name="trade_drafts")
    op.drop_index(op.f("ix_trade_drafts_mentor_id"), table_name="trade_drafts")
    op.drop_index(op.f("ix_trade_drafts_matched_trade_id"), table_name="trade_drafts")
    op.drop_index(op.f("ix_trade_drafts_guild_id"), table_name="trade_drafts")
    op.drop_table("trade_drafts")
    op.drop_index(op.f("ix_trades_mentor_id"), table_name="trades")
    op.drop_index("ix_trades_guild_state_category", table_name="trades")
    op.drop_index(op.f("ix_trades_guild_id"), table_name="trades")
    op.drop_table("trades")
    op.drop_index(op.f("ix_source_attachments_source_message_id"), table_name="source_attachments")
    op.drop_table("source_attachments")
    op.drop_index(op.f("ix_mentor_aliases_mentor_id"), table_name="mentor_aliases")
    op.drop_index(op.f("ix_mentor_aliases_guild_id"), table_name="mentor_aliases")
    op.drop_table("mentor_aliases")
    op.drop_index(op.f("ix_membership_events_membership_id"), table_name="membership_events")
    op.drop_index("ix_membership_events_membership_created", table_name="membership_events")
    op.drop_table("membership_events")
    op.drop_index(op.f("ix_subscriptions_user_id"), table_name="subscriptions")
    op.drop_index(op.f("ix_subscriptions_guild_id"), table_name="subscriptions")
    op.drop_table("subscriptions")
    op.drop_index(op.f("ix_source_messages_submitted_by"), table_name="source_messages")
    op.drop_index(op.f("ix_source_messages_guild_id"), table_name="source_messages")
    op.drop_table("source_messages")
    op.drop_index(op.f("ix_scheduled_jobs_guild_id"), table_name="scheduled_jobs")
    op.drop_index("ix_scheduled_jobs_due", table_name="scheduled_jobs")
    op.drop_table("scheduled_jobs")
    op.drop_index(op.f("ix_mentors_guild_id"), table_name="mentors")
    op.drop_table("mentors")
    op.drop_index(op.f("ix_memberships_user_id"), table_name="memberships")
    op.drop_index(op.f("ix_memberships_guild_id"), table_name="memberships")
    op.drop_index(op.f("ix_memberships_ends_at"), table_name="memberships")
    op.drop_table("memberships")
    op.drop_index(op.f("ix_audit_logs_guild_id"), table_name="audit_logs")
    op.drop_index("ix_audit_logs_guild_created", table_name="audit_logs")
    op.drop_index(op.f("ix_audit_logs_actor_user_id"), table_name="audit_logs")
    op.drop_table("audit_logs")
    op.drop_table("guild_config")
    # ### end Alembic commands ###
